BreadthFirst: Board.class Controller.class BreadthFirst.class

Board.class: Board.java
	javac Board.java

Controller.class: Controller.java
	javac Controller.java

BreadthFirst.class: BreadthFirst.java
	javac BreadthFirst.java

run: 
	java BreadthFirst

clean: 
	rm *.class