AStar: Board.class AStarController.class AStar.class

Board.class: Board.java
	javac Board.java

AStarController.class: AStarController.java
	javac AStarController.java

AStar.class: AStar.java
	javac AStar.java

run: 
	java AStar

clean: 
	rm *.class